# Generated by Django 4.1.5 on 2023-03-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='User',
        ),
    ]
