# Generated by Django 4.1.5 on 2023-04-04 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_rename_students_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwd',
            new_name='passwrd',
        ),
        migrations.AddField(
            model_name='user',
            name='studId',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
